export const types = {
  FETCH_JOKES_REQUESTED: "FETCH_JOKES_REQUESTED",
  FETCH_JOKES_SUCCESS: "FETCH_JOKES_SUCCESS",
  FETCH_JOKES_ERROR: "FETCH_JOKES_ERROR",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  FILTER_JOKES: "FILTER_JOKES",
};
